LITS_System/LITS_System/urls.py
from django.contrib import admin
from django.urls import path, include
from application import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


handler404 = 'application.views.error_404'
handler500 = 'application.views.error_500'

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PayrollAttendanceIndexPage.as_view(), name="index"),
    path('employee/index/', views.PayrallAttendanceEmployeeIndexPage.as_view(), name="employee_index"),
    
    # Update password    
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset
    path('accounts/password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Login and register
    path('login/', views.login_page, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', views.register_page, name="register"), 

    path('application/', include('application.urls')),

    # path('error500/', views.error_500, name="error500"), 
    # path('error404/', views.error_404, name="error404"), 
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITS_System/application/urls.py
from django.urls import path
from application import views

app_name = "application"

urlpatterns = [
    path('user/profile/', views.user_profile, name='user_profile'),
    path('user/new/profile/', views.new_profile, name='new_user_profile'),
    path('user/edit/profile/', views.edit_profile, name='edit_user_profile'),
    path('user/profile/image/', views.save_profile_image, name='save_profile_image'),
    path('user/profile/mobile_number/', views.add_mobile_number, name='add_mobile_number'),
    path('user/profile/mobile_number/delete/<int:id>/', views.delete_mobile_number, name='delete_mobile_number'),
    path('user/profile/skill/', views.add_skill, name='add_skill'),
    path('user/profile/skill/delete/<int:id>/', views.delete_skill, name='delete_skill'),
    path('user/new/company/details/', views.new_company_details, name='new_company_details'),
    path('user/edit/company/details/', views.edit_company_details, name='edit_company_details'),
    path('user/profile/telephone_number/', views.add_telephone_number, name='add_telephone_number'),
    path('user/profile/telephone_number/delete/<int:id>/', views.delete_telephone_number, name='delete_telephone_number'),
    path('attendance/cutoff/', views.cut_off_page, name="cut_off_page"),    
    path('employees/employee/list/', views.employee_list_page, name="employee_list"),
    path('employees/employee/list/payroll/settings/<str:key>/', views.employee_payroll_base_salary_settings, name="employee_payroll_settings"),
    path('employees/employee/delete/<int:id>/', views.delete_employee, name="delete_employee"),
    path('attendance/cutoff/upload/', views.upload_attendance, name="upload_attendance"),
    path('attendance/cutoff/delete/<int:id>/', views.delete_attendance, name="delete_attendance"),
    path('employees/attendance/view/<str:pk>/', views.employee_attendance, name="employee_attendance_view"),
    path('employees/attendance/view/cutoff/<str:pk>/<int:id>/', views.employee_attendance_cutoff, name="employee_attendance_cut_off_view"),
    path('employees/attendance/view/cutoff/manual/<str:pk>/<int:id>/', views.employee_attendance_manual_configuration, name="employee_attendance_cut_off_manual"),
    path('employees/payroll/manage/', views.employee_payroll_page, name="employee_payroll_manage"),
    path('employees/payroll/manage/cutoff/<int:id>/', views.employee_payroll_employee_list, name="employee_payroll_manage_employee_list"),
    path('employees/payroll/manage/cutoff/create/payroll/<str:key>/<int:id>/', views.employee_create_payroll, name="employee_create_payroll"),
    path('employees/payroll/manage/cutoff/edit/payroll/<str:key>/<int:id>/', views.employee_edit_payroll, name="employee_edit_payroll"),
    path('employees/payroll/manage/cutoff/delete/payroll/<str:key>/<int:id>/', views.employee_delete_payroll, name="employee_delete_payroll"),
    path('employees/manage/leaves/', views.employee_manage_leaves, name="employee_manage_leaves_page"),
    path('employees/manage/leaves/view/<int:id>/', views.employee_view_employee_leaves, name="employee_view_employee_leaves_page"),
    path('employees/manage/iteneraries/', views.employee_manage_itenerary, name="employee_manage_iteneraries_page"),
    path('employees/manage/iteneraries/view/<int:id>/', views.employee_view_itenerary, name="employee_view_iteneraries_page"),
    path('employees/manage/admin/concerns/', views.employee_manage_concerns, name="employee_manage_concerns_page"),
    path('employees/manage/admin/concerns/create/', views.employee_create_concern, name="employee_create_concerns_page"),
    path('employees/manage/admin/concerns/edit/<int:id>/', views.employee_edit_concern, name="employee_edit_concerns_page"),
    path('employees/manage/admin/concerns/view/<int:id>/', views.employee_view_concern, name="employee_view_concerns_page"),
    path('employees/manage/admin/concerns/delete/<int:id>/', views.employee_delete_concern , name="employee_delete_concerns_page"),
    path('employees/manage/admin/concerns/inbox/', views.employee_manage_inbox_concern, name="employee_manage_inbox_concerns_page"),
    path('employees/manage/admin/concerns/reply/<int:id>/', views.employee_reply_concern , name="employee_reply_concerns_page"),
    path('employees/manage/reports/', views.reports_page, name="employee_reports"),
    
    path('users/nofitications/manager/delete/<int:id>/', views.read_notifications, name="users_notifications_delete"),
    path('users/nofitications/manager/delete/all/', views.read_all_notifications, name="users_notifications_delete_all"),
    path('users/maintainancepage/',views.maintainance_page, name="users_maintainance_page"),


    #employee side
    path('employee/profile/', views.employee_profile, name='employee_profile'),
    path('employee/attendance/cutoffandpayroll/', views.side_employee_cut_off_payroll_page, name="employee_side_cutoff_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/attendance/<int:id>/', views.side_employee_cut_off_page, name="employee_side_cutoff_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/<int:id>/', views.side_employee_view_payroll_page, name="employee_side_view_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/print/<int:id>/', views.side_employee_print_payroll_page, name="employee_side_print_payroll_page"),
    path('employee/manage/leaves/', views.side_employee_manage_leaves_page, name="employee_side_manage_leaves_page"),
    path('employee/manage/leaves/create/', views.side_employee_create_leave_form, name="employee_side_create_leave_form"),
    path('employee/manage/leaves/edit/<int:id>/', views.side_employee_edit_leave_form, name="employee_side_edit_leave_form"),
    path('employee/manage/leaves/delete/<int:id>/', views.side_employee_delete_leave_form, name="employee_side_delete_leave_form"),
    path('employee/manage/leaves/view/<int:id>/', views.side_employee_view_leave_form, name="employee_side_view_leave_form"),
    path('employee/manage/iteneraries/', views.side_employee_manage_inteneraries, name="employee_side_manage_iteneraries_page"),
    path('employee/manage/iteneraries/create/', views.side_employee_create_inteneraries, name="employee_side_create_iteneraries_page"),
    path('employee/manage/iteneraries/edit/<int:id>/', views.side_employee_edit_inteneraries, name="employee_side_edit_iteneraries_page"),
    path('employee/manage/iteneraries/delete/<int:id>/', views.side_employee_delete_inteneraries, name="employee_side_delete_iteneraries_page"),
    path('employee/manage/iteneraries/view/<int:id>/', views.side_employee_view_itenerary_form, name="employee_side_view_iteneraries_page"),
    path('employee/manage/concerns/', views.side_employee_manage_concerns, name="employee_side_manage_concerns_page"),
    path('employee/manage/concerns/create/', views.side_employee_create_concern, name="employee_side_create_concerns_page"),
    path('employee/manage/concerns/edit/<int:id>/', views.side_employee_edit_concern, name="employee_side_edit_concerns_page"),
    path('employee/manage/concerns/delete/<int:id>/', views.side_employee_delete_concern, name="employee_side_delete_concerns_page"),
    path('employee/manage/concerns/view/<int:id>/', views.side_employee_view_concern, name="employee_side_view_concerns_page"),
    path('employee/manage/concerns/inbox/', views.side_employee_manage_inbox_concern, name="employee_side_manage_inbox_concerns_page"),
    path('employee/manage/concerns/reply/<int:id>/', views.side_employee_reply_concern, name="employee_side_reply_concerns_page"),
    path('employee/maintainancepage/', views.employee_side_maintainance_page, name="employee_side_maintainance_page"),
    
]

LITS_System/application/templates/profiles/add_mobile_number.html
<form class="add-mobile-number-form" method="POST" data-url="{% url 'application:add_mobile_number' %}">
    {% csrf_token %}

    <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Mobile Number</h4>
    </div>
    <div class="modal-body">
        <p>Please enter your mobile number&hellip;</p>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-ban"></i> Error!</h4>
            {{ form.mobile_number.errors|striptags }}
        </div>
        {% endif %}
        <div class="box-body"> 
            <div class="input-group"> 
                <span class="input-group-addon"><i class="fa fa-fw fa-mobile-phone"></i></span>
                {{ form.mobile_number }}
              </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>        
        <button type="submit" class="btn btn-primary">Save changes</button>
        <!-- <input type="submit"  class="btn btn-primary" value="Add/Save"> -->
    </div>
</form>

LITS_System/application/templates/profiles/add_skills.html
<form class="add-skill-form" method="POST" data-url="{% url 'application:add_skill' %}">
    {% csrf_token %}

    <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Skill</h4>
    </div>
    <div class="modal-body">
        <p>Select your additional skill&hellip;</p>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-ban"></i> Error!</h4>
            {{ form.skills.errors|striptags }}
        </div>
        {% endif %}
        <div class="box-body"> 
            <div class="input-group"> 
                <span class="input-group-addon"><i class="fa fa-fw fa-search"></i></span>
                {{ form.skills }}
              </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>        
        <button type="submit" class="btn btn-primary">Save changes</button>
        <!-- <input type="submit"  class="btn btn-primary" value="Add/Save"> -->
    </div>
</form>

LITS_System/application/templates/profiles/add_telephone_number.html
<form class="add-telephone-number-form" method="POST" data-url="{% url 'application:add_telephone_number' %}">
    {% csrf_token %}

    <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Telephone Number</h4>
    </div>
    <div class="modal-body">
        <p>Please enter your telephone number&hellip;</p>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h4><i class="icon fa fa-ban"></i> Error!</h4>
            {{ form.telephone_number.errors|striptags }}
        </div>
        {% endif %}
        <div class="box-body"> 
            <div class="input-group"> 
                <span class="input-group-addon"><i class="fa fa-fw fa-mobile-phone"></i></span>
                {{ form.telephone_number }}
              </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>        
        <button type="submit" class="btn btn-primary">Save changes</button>
        <!-- <input type="submit"  class="btn btn-primary" value="Add/Save"> -->
    </div>
</form>

LITS_System/application/templates/profiles/edit_company_details.html
{% load staticfiles %}
<form class="edit-company-details-form" method="POST" enctype="multipart/form-data" data-url="{% url 'application:edit_company_details' %}">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Company Details</h4>
      </div>

      <div class="modal-body">
        <p>Please fill-up all information&hellip;</p>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Form Validation Error!</h4>
          {{ form.company_id.errors|striptags }}
          {{ form.company_tin.errors|striptags }}
          {{ form.designation.errors|striptags }}
          {{ form.personal_tin.errors|striptags }}
          {{ form.sss_number.errors|striptags }}
          {{ form.pagibig.errors|striptags }}
          {{ form.philhealth.errors|striptags }} 
        </div>
        {% endif %}

            <!-- /.form group -->
        <div class="form-group">
            <label for="{{ form.company_id.id_for_label }}">Company ID:</label>
            {{ form.company_id }}
        </div>
        <div class="form-group">
            <label for="{{ form.company_tin.id_for_label }}">Company TIN:</label>
            {{ form.company_tin }}
        </div>
        <div class="form-group">
            <label for="{{ form.designation.id_for_label }}">Designation:</label>
            {{ form.designation }}
        </div>
        <div class="form-group">
          <label for="{{ form.designation.id_for_label }}">Department:</label>
          {{ form.department }}
        </div>
        <div class="form-group">
            <label for="{{ form.personal_tin.id_for_label }}">Personal TIN:</label>
            {{ form.personal_tin }}
        </div>
        <div class="form-group">
            <label for="{{ form.sss_number.id_for_label }}">SSS Number:</label>
            {{ form.sss_number }}
        </div>

        <div class="form-group">
            <label for="{{ form.pagibig.id_for_label }}">Pag-ibig:</label>
            {{ form.pagibig }}
        </div>

        <div class="form-group">
            <label for="{{ form.philhealth.id_for_label }}">Philhealth:</label>
            {{ form.philhealth }}
        </div>


      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div> 
</form>

LITS_System/application/templates/profiles/edit_profile_personal.html
{% load staticfiles %}
<form id="frmNewProfile" class="new-profile-form" method="POST" enctype="multipart/form-data"
  data-url="{% url 'application:edit_user_profile' %}">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Edit Profile</h4>
  </div>
  <div class="modal-body">
    <p>Please fill-up all information&hellip;</p>
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Form Validation Error!</h4>
      {{ form.suffix.errors|striptags }}
      {{ form.first_name.errors|striptags }}
      {{ form.middle_name.errors|striptags }}
      {{ form.last_name.errors|striptags }}
      {{ form.dob.errors|striptags }}
      {{ form.gender.errors|striptags }}
      {{ form.age.errors|striptags }}
      {{ form.address.errors|striptags }}
      {{ form.date_started.errors|striptags }}
      {{ form.education.errors|striptags }}
      {{ form.experience.errors|striptags }}
      {{ form.notes.errors|striptags }}
      {{ form.emer_cont_pers.errors|striptags }}
      {{ form.emer_cont_pers_cont_no.errors|striptags }}
    </div>
    {% endif %}
    <div class="box-body">

      <!-- /.form group -->
      <div class="form-group">
        <label for="{{ form.suffix.id_for_label }}">Suffix (If any.)</label>
        {{ form.suffix }}
      </div>
      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">First name</label>
        {{ form.first_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.middle_name.id_for_label }}">Middle name</label>
        {{ form.middle_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Last name</label>
        {{ form.last_name }}
      </div>

      <div class="form-group">
        <label>Date of birth:</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          {{ form.dob }}
        </div>
        <!-- /.input group -->
      </div>

      <div class="form-group">
        <label for="{{ form.gender.id_for_label }}">Gender</label>
        {{ form.gender }}
      </div>

    
      
      <div class="form-group">
        <label for="{{ form.age.id_for_label }}">Age</label>
        {{ form.age }}
      </div>

      <div class="form-group">
        <label for="{{ form.address.id_for_label }}">Address</label>
        {{ form.address }}
      </div>

      <div class="form-group">
        <label>Date Started:</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          {{ form.date_started }}
        </div>
        <!-- /.input group -->
      </div>

      <div class="form-group">
        <label for="{{ form.education.id_for_label }}">Education</label>
        {{ form.education }}
      </div>

      <div class="form-group">
        <label for="{{ form.experience.id_for_label }}">Experience</label>
        {{ form.experience }}
      </div>

      <div class="form-group">
        <label for="{{ form.notes.id_for_label }}">Notes</label>
        {{ form.notes }}
      </div>

      <div class="form-group">
        <label for="{{ form.emer_cont_pers.id_for_label }}">Emergency Contact Person</label>
        {{ form.emer_cont_pers }}
      </div>

      <div class="form-group">
        <label for="{{ form.emer_cont_pers_cont_no.id_for_label }}">Emergency Contact Person Number</label>
        {{ form.emer_cont_pers_cont_no }}
      </div>

    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
</form>


<script>

  //Datemask dd/mm/yyyy
  //$('#datepicker').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });
  //Date picker
  //Initialize Select2 Elements
  $('.select2').select2();
  $('#dob').datepicker({
    autoclose: true
  });
  $('#date_started').datepicker({
    autoclose: true
  });



</script>

LITS_System/application/templates/profiles/new_company_details.html
{% load staticfiles %}
<form class="new-company-details-form" method="POST" enctype="multipart/form-data" data-url="{% url 'application:new_company_details' %}">
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create Company Details</h4>
      </div>

      <div class="modal-body">
        <p>Please fill-up all information&hellip;</p>
        {% if form.errors %}
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <h4><i class="icon fa fa-ban"></i> Form Validation Error!</h4>
          {{ form.company_id.errors|striptags }}
          {{ form.company_tin.errors|striptags }}
          {{ form.designation.errors|striptags }}
          {{ form.personal_tin.errors|striptags }}
          {{ form.sss_number.errors|striptags }}
          {{ form.pagibig.errors|striptags }}
          {{ form.philhealth.errors|striptags }} 
        </div>
        {% endif %}

            <!-- /.form group -->
        <div class="form-group">
            <label for="{{ form.company_id.id_for_label }}">Company ID:</label>
            {{ form.company_id }}
        </div>
        <div class="form-group">
            <label for="{{ form.company_tin.id_for_label }}">Company TIN:</label>
            {{ form.company_tin }}
        </div>
        <div class="form-group">
            <label for="{{ form.designation.id_for_label }}">Designation:</label>
            {{ form.designation }}
        </div>
        <div class="form-group">
          <label for="{{ form.designation.id_for_label }}">Department:</label>
          {{ form.department }}
        </div>
        <div class="form-group">
            <label for="{{ form.personal_tin.id_for_label }}">Personal TIN:</label>
            {{ form.personal_tin }}
        </div>
        <div class="form-group">
            <label for="{{ form.sss_number.id_for_label }}">SSS Number:</label>
            {{ form.sss_number }}
        </div>

        <div class="form-group">
            <label for="{{ form.pagibig.id_for_label }}">Pag-ibig:</label>
            {{ form.pagibig }}
        </div>

        <div class="form-group">
            <label for="{{ form.philhealth.id_for_label }}">Philhealth:</label>
            {{ form.philhealth }}
        </div>


      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div> 
</form>

LITS_System/application/templates/profiles/new_profile_personal.html
{% load staticfiles %}
<form id="frmNewProfile" class="new-profile-form" method="POST" enctype="multipart/form-data" data-url="{% url 'application:new_user_profile' %}">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">Create Profile</h4>
  </div>
  <div class="modal-body">
    <p>Please fill-up all information&hellip;</p>
    {% if form.errors %}
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><i class="icon fa fa-ban"></i> Form Validation Error!</h4>
      {{ form.suffix.errors|striptags }}
      {{ form.first_name.errors|striptags }}
      {{ form.middle_name.errors|striptags }}
      {{ form.last_name.errors|striptags }}
      {{ form.dob.errors|striptags }}
      {{ form.gender.errors|striptags }}
      {{ form.age.errors|striptags }}
      {{ form.address.errors|striptags }}
      {{ form.date_started.errors|striptags }}
      {{ form.education.errors|striptags }}
      {{ form.experience.errors|striptags }}
      {{ form.notes.errors|striptags }}
      {{ form.emer_cont_pers.errors|striptags }}
      {{ form.emer_cont_pers_cont_no.errors|striptags }}
    </div>
    {% endif %}
    <div class="box-body">

      <!-- /.form group -->
      <div class="form-group">
        <label for="{{ form.suffix.id_for_label }}">Suffix (If any.)</label>
        {{ form.suffix }}
      </div>
      <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">First name</label>
        {{ form.first_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.middle_name.id_for_label }}">Middle name</label>
        {{ form.middle_name }}
      </div>
      <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Last name</label>
        {{ form.last_name }}
      </div>

      <div class="form-group">
        <label>Date of birth:</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          {{ form.dob }}
        </div>
        <!-- /.input group -->
      </div>
 

      <div class="form-group">
        <label for="{{ form.gender.id_for_label }}">Gender</label>
        {{ form.gender }}
      </div>

      <div class="form-group">
        <label for="{{ form.age.id_for_label }}">Age</label>
        {{ form.age }}
      </div>

      <div class="form-group">
        <label for="{{ form.address.id_for_label }}">Address</label>
        {{ form.address }}
      </div>

      <div class="form-group">
        <label>Date Started:</label>
        <div class="input-group date">
          <div class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </div>
          {{ form.date_started }}
        </div>
        <!-- /.input group -->
      </div> 

      <div class="form-group">
        <label for="{{ form.education.id_for_label }}">Education</label>
        {{ form.education }}
      </div>

      <div class="form-group">
        <label for="{{ form.experience.id_for_label }}">Experience</label>
        {{ form.experience }}
      </div>

      <div class="form-group">
        <label for="{{ form.notes.id_for_label }}">Notes</label>
        {{ form.notes }}
      </div>

      <div class="form-group">
        <label for="{{ form.emer_cont_pers.id_for_label }}">Emergency Contact Person</label>
        {{ form.emer_cont_pers }}
      </div>

      <div class="form-group">
        <label for="{{ form.emer_cont_pers_cont_no.id_for_label }}">Emergency Contact Person Number</label>
        {{ form.emer_cont_pers_cont_no }}
      </div>
 
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div> 
</form>


<script>

  //Datemask dd/mm/yyyy
  //$('#datepicker').inputmask('dd/mm/yyyy', { 'placeholder': 'dd/mm/yyyy' });
  //Date picker
  //Initialize Select2 Elements
  $('.select2').select2();
  $('#dob').datepicker({
    autoclose: true
  });
  $('#date_started').datepicker({
    autoclose: true
  });



</script>