LITS_System/LITS_System/urls.py
from django.contrib import admin
from django.urls import path, include
from application import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


handler404 = 'application.views.error_404'
handler500 = 'application.views.error_500'

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PayrollAttendanceIndexPage.as_view(), name="index"),
    path('employee/index/', views.PayrallAttendanceEmployeeIndexPage.as_view(), name="employee_index"),
    
    # Update password    
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset
    path('accounts/password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Login and register
    path('login/', views.login_page, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', views.register_page, name="register"), 

    path('application/', include('application.urls')),

    # path('error500/', views.error_500, name="error500"), 
    # path('error404/', views.error_404, name="error404"), 
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITS_System/application/urls.py
from django.urls import path
from application import views

app_name = "application"

urlpatterns = [
    path('user/profile/', views.user_profile, name='user_profile'),
    path('user/new/profile/', views.new_profile, name='new_user_profile'),
    path('user/edit/profile/', views.edit_profile, name='edit_user_profile'),
    path('user/profile/image/', views.save_profile_image, name='save_profile_image'),
    path('user/profile/mobile_number/', views.add_mobile_number, name='add_mobile_number'),
    path('user/profile/mobile_number/delete/<int:id>/', views.delete_mobile_number, name='delete_mobile_number'),
    path('user/profile/skill/', views.add_skill, name='add_skill'),
    path('user/profile/skill/delete/<int:id>/', views.delete_skill, name='delete_skill'),
    path('user/new/company/details/', views.new_company_details, name='new_company_details'),
    path('user/edit/company/details/', views.edit_company_details, name='edit_company_details'),
    path('user/profile/telephone_number/', views.add_telephone_number, name='add_telephone_number'),
    path('user/profile/telephone_number/delete/<int:id>/', views.delete_telephone_number, name='delete_telephone_number'),
    path('attendance/cutoff/', views.cut_off_page, name="cut_off_page"),    
    path('employees/employee/list/', views.employee_list_page, name="employee_list"),
    path('employees/employee/list/payroll/settings/<str:key>/', views.employee_payroll_base_salary_settings, name="employee_payroll_settings"),
    path('employees/employee/delete/<int:id>/', views.delete_employee, name="delete_employee"),
    path('attendance/cutoff/upload/', views.upload_attendance, name="upload_attendance"),
    path('attendance/cutoff/delete/<int:id>/', views.delete_attendance, name="delete_attendance"),
    path('employees/attendance/view/<str:pk>/', views.employee_attendance, name="employee_attendance_view"),
    path('employees/attendance/view/cutoff/<str:pk>/<int:id>/', views.employee_attendance_cutoff, name="employee_attendance_cut_off_view"),
    path('employees/attendance/view/cutoff/manual/<str:pk>/<int:id>/', views.employee_attendance_manual_configuration, name="employee_attendance_cut_off_manual"),
    path('employees/payroll/manage/', views.employee_payroll_page, name="employee_payroll_manage"),
    path('employees/payroll/manage/cutoff/<int:id>/', views.employee_payroll_employee_list, name="employee_payroll_manage_employee_list"),
    path('employees/payroll/manage/cutoff/create/payroll/<str:key>/<int:id>/', views.employee_create_payroll, name="employee_create_payroll"),
    path('employees/payroll/manage/cutoff/edit/payroll/<str:key>/<int:id>/', views.employee_edit_payroll, name="employee_edit_payroll"),
    path('employees/payroll/manage/cutoff/delete/payroll/<str:key>/<int:id>/', views.employee_delete_payroll, name="employee_delete_payroll"),
    path('employees/manage/leaves/', views.employee_manage_leaves, name="employee_manage_leaves_page"),
    path('employees/manage/leaves/view/<int:id>/', views.employee_view_employee_leaves, name="employee_view_employee_leaves_page"),
    path('employees/manage/iteneraries/', views.employee_manage_itenerary, name="employee_manage_iteneraries_page"),
    path('employees/manage/iteneraries/view/<int:id>/', views.employee_view_itenerary, name="employee_view_iteneraries_page"),
    path('employees/manage/admin/concerns/', views.employee_manage_concerns, name="employee_manage_concerns_page"),
    path('employees/manage/admin/concerns/create/', views.employee_create_concern, name="employee_create_concerns_page"),
    path('employees/manage/admin/concerns/edit/<int:id>/', views.employee_edit_concern, name="employee_edit_concerns_page"),
    path('employees/manage/admin/concerns/view/<int:id>/', views.employee_view_concern, name="employee_view_concerns_page"),
    path('employees/manage/admin/concerns/delete/<int:id>/', views.employee_delete_concern , name="employee_delete_concerns_page"),
    path('employees/manage/admin/concerns/inbox/', views.employee_manage_inbox_concern, name="employee_manage_inbox_concerns_page"),
    path('employees/manage/admin/concerns/reply/<int:id>/', views.employee_reply_concern , name="employee_reply_concerns_page"),
    path('employees/manage/reports/', views.reports_page, name="employee_reports"),
    
    path('users/nofitications/manager/delete/<int:id>/', views.read_notifications, name="users_notifications_delete"),
    path('users/nofitications/manager/delete/all/', views.read_all_notifications, name="users_notifications_delete_all"),
    path('users/maintainancepage/',views.maintainance_page, name="users_maintainance_page"),


    #employee side
    path('employee/profile/', views.employee_profile, name='employee_profile'),
    path('employee/attendance/cutoffandpayroll/', views.side_employee_cut_off_payroll_page, name="employee_side_cutoff_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/attendance/<int:id>/', views.side_employee_cut_off_page, name="employee_side_cutoff_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/<int:id>/', views.side_employee_view_payroll_page, name="employee_side_view_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/print/<int:id>/', views.side_employee_print_payroll_page, name="employee_side_print_payroll_page"),
    path('employee/manage/leaves/', views.side_employee_manage_leaves_page, name="employee_side_manage_leaves_page"),
    path('employee/manage/leaves/create/', views.side_employee_create_leave_form, name="employee_side_create_leave_form"),
    path('employee/manage/leaves/edit/<int:id>/', views.side_employee_edit_leave_form, name="employee_side_edit_leave_form"),
    path('employee/manage/leaves/delete/<int:id>/', views.side_employee_delete_leave_form, name="employee_side_delete_leave_form"),
    path('employee/manage/leaves/view/<int:id>/', views.side_employee_view_leave_form, name="employee_side_view_leave_form"),
    path('employee/manage/iteneraries/', views.side_employee_manage_inteneraries, name="employee_side_manage_iteneraries_page"),
    path('employee/manage/iteneraries/create/', views.side_employee_create_inteneraries, name="employee_side_create_iteneraries_page"),
    path('employee/manage/iteneraries/edit/<int:id>/', views.side_employee_edit_inteneraries, name="employee_side_edit_iteneraries_page"),
    path('employee/manage/iteneraries/delete/<int:id>/', views.side_employee_delete_inteneraries, name="employee_side_delete_iteneraries_page"),
    path('employee/manage/iteneraries/view/<int:id>/', views.side_employee_view_itenerary_form, name="employee_side_view_iteneraries_page"),
    path('employee/manage/concerns/', views.side_employee_manage_concerns, name="employee_side_manage_concerns_page"),
    path('employee/manage/concerns/create/', views.side_employee_create_concern, name="employee_side_create_concerns_page"),
    path('employee/manage/concerns/edit/<int:id>/', views.side_employee_edit_concern, name="employee_side_edit_concerns_page"),
    path('employee/manage/concerns/delete/<int:id>/', views.side_employee_delete_concern, name="employee_side_delete_concerns_page"),
    path('employee/manage/concerns/view/<int:id>/', views.side_employee_view_concern, name="employee_side_view_concerns_page"),
    path('employee/manage/concerns/inbox/', views.side_employee_manage_inbox_concern, name="employee_side_manage_inbox_concerns_page"),
    path('employee/manage/concerns/reply/<int:id>/', views.side_employee_reply_concern, name="employee_side_reply_concerns_page"),
    path('employee/maintainancepage/', views.employee_side_maintainance_page, name="employee_side_maintainance_page"),
    
]

LITS_System/application/templates/employees/employee_attendance_list.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block title %}
Employee Attendance List Page
{% endblock title%}


{% block css %}
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">


<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
<!-- bootstrap datepicker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/all.css' %}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="{% static 'plugins/timepicker/bootstrap-timepicker.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

<!-- Google Font -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


<!-- Select2 -->
<link rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">

<link rel="stylesheet" href="{% static 'css/loading-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/loading.css' %}">

{% endblock css %}

{% block nav_dashboard %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li class=""><a href="{% url 'index' %}"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
        <!-- <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li> -->
    </ul>
</li>
{% endblock nav_dashboard %}

{% block nav_employees %}
<li class="active treeview">
    <a href="#">
        <i class="fa fa-fw fa-group"></i> <span>Employees</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li class="active"><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i> List
                Employees</a></li>
        <li><a href="{% url 'application:employee_payroll_manage' %}"><i class="fa fa-fw fa-credit-card"></i> Manage Payroll</a></li>
        <li><a href="{% url 'application:employee_manage_leaves_page' %}"><i class="fa fa-fw fa-car"></i> Leaves </a></li>
        <li><a href="{% url 'application:employee_manage_iteneraries_page' %}"><i class="fa fa-fw fa-calendar-times-o"></i> Iteneraries </a></li>
        <li><a href="{% url 'application:employee_manage_concerns_page' %}"><i class="fa fa-fw fa-commenting"></i> Concerns</a></li>
    </ul>
</li>
{% endblock nav_employees %}


{% block main_content %}
<section class="content-header">
    <h1>
        Employee Attendance List
        <small>Manage details</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active"><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i>Employee List</a></li>
        <li class="active"><i class="fa fa-fw fa-calendar-plus-o"></i> Attendance List</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">Employee Attendance Table</h3>
                </div>
                <div class="box-body">
                    <table id="tblEmployeeAttendanceList" class="table table-bordered table-striped text-center">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Cut-Off Period</th>
                                <th>Date Uploaded</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for cut_off_period  in cut_off_period_list %}
                            <tr>
                                <td>{{ cut_off_period.id}}</td> 
                                <td> <span class="label label-warning">{{ cut_off_period.cut_off_period}} </span></td>
                                <td>{{ cut_off_period.date_created}}</td> 
                                
                                <td> 
                                    <div class="btn-group-vertical"> 
                                        <a href="{% url 'application:employee_attendance_cut_off_view' employee.key_id cut_off_period.id %}" class="btn btn-block btn-success" data-toggle="tooltip"
                                        title="Manage Attendance">
                                        <span class="fa fa-fw fa-gears"></span>
                                            Manage
                                    </a>
                             
                                    </div>
                             
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th>ID</th>
                                <th>Cut-Off Period</th>
                                <th>Date Uploaded</th> 
                                <th>Action</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>



{% block js %}


{% endblock js %}

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>

<!-- DataTables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
 

<script>
    $(function () {


        $('#tblEmployeeAttendanceList').DataTable({
            'columnDefs': [ {
                'targets': 3, /* column index */
                'orderable': false, /* true or false */
            }]
        });
        // $('#example2').DataTable({
        //     'paging'      : true,
        //     'lengthChange': false,
        //     'searching'   : false,
        //     'ordering'    : true,
        //     'info'        : true,
        //     'autoWidth'   : false
        //   })
    });
</script>
{% endblock main_content %}

LITS_System/application/templates/employees/employee_cutoff_page.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block title %}
Employee Attendance Cut-Off Page
{% endblock title%}

{% block css %}
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">
 

<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
<!-- bootstrap datepicker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/all.css' %}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="{% static 'plugins/timepicker/bootstrap-timepicker.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

<!-- Google Font -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


 
{% endblock css %}


{% block nav_dashboard %}
<li class="treeview">
  <a href="#">
    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
    <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
  </a>
  <ul class="treeview-menu">
    <li class=""><a href="{% url 'index' %}"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
    <!-- <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li> -->
  </ul>
</li>
{% endblock nav_dashboard %}     

{% block nav_employees %}
<li class="active treeview">
    <a href="#">
        <i class="fa fa-fw fa-group"></i> <span>Employees</span>
        <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
        </span>
    </a>
    <ul class="treeview-menu">
        <li class="active"><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i> List
                Employees</a></li>
        <li><a href="{% url 'application:employee_payroll_manage' %}"><i class="fa fa-fw fa-credit-card"></i> Manage Payroll</a></li>
        <li><a href="{% url 'application:employee_manage_leaves_page' %}"><i class="fa fa-fw fa-car"></i> Leaves </a></li>
        <li><a href="{% url 'application:employee_manage_iteneraries_page' %}"><i class="fa fa-fw fa-calendar-times-o"></i> Iteneraries </a></li>
        <li><a href="{% url 'application:employee_manage_concerns_page' %}"><i class="fa fa-fw fa-commenting"></i> Concerns</a></li>
    </ul>
</li>
{% endblock nav_employees %}

{% block main_content %}

<section class="content-header">
    <h1>
        Employee Attendance Cut-Off List
        <small>Manage details</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class=""><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i>Employee List</a></li>
        <li class=""><a href="{% url 'application:employee_attendance_view' employee.key_id %}"><i class="fa fa-fw fa-calendar-plus-o"></i>Attendance List</a></li> 
        <li class="active">{{ cutoff.cut_off_period }}</li>
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <form id="employee_attendance_cut_off_table" method="POST" data-url="{% url 'application:employee_attendance_cut_off_view' employee.key_id cutoff.id %}">
                {% csrf_token %}
                {% include 'partials/_messages.html' %}
                {% if not is_available %}
                <div class="callout callout-danger">
                <h4>Oops! The cut-off period was not available!</h4>

                <p>The possible issue is that the name or identity of the this employee was not matched on the uploaded attendance and the record was not proccessed or the attendance record was deleted. <strong>You can set it manually </strong><a href="{% url 'application:employee_attendance_cut_off_manual' employee.key_id cutoff.id %}">Here</a>.</p>
                </div>
                {% else %}
                <div class="box"> 
                    <div class="box-header with-border">
                        <h3 class="box-title">Employee Attendance Cut-Off Period Table <strong>({{ cutoff.cut_off_period }})</strong></h3>
                    </div>
                    <div class="box-body"> 
                        <table class="table table-bordered">
                            <tr>
                                <th>Days of week</th>
                                <th>Date</th>
                                <th>Time In</th>
                                <th>Time Out</th>
                                <th>Late (Min)</th>
                                <th>Undertime (Min)</th>
                                <th>Computing Pay for Work Done on</th>
                                <th>Overtime (Hour)</th>
                                <th>Computing Overtime</th>
                            </tr>
                            <!-- tbody -->
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                            <!-- ModelFormsets require form.id. It is rendered as a hidden field. You will need to implement it with both formsets. -->
                            {% for hidden in form.hidden_fields %}
                            {{ hidden }}
                            {% endfor %}
                            {{ form.non_field_errors }}
                            {{ form.errors }}
                            <tr>
                                <td>{{form.days_of_week}}</td>
                                <td>{{form.date}}</td>
                                <td>
                                    <div class="input-group">
                                        {{form.time_in}} 
                                        <div class="input-group-addon">
                                            <i class="fa fa-clock-o"></i>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="input-group">
                                        {{form.time_out}}
                                        <div class="input-group-addon">
                                            <i class="fa fa-clock-o"></i>
                                        </div>
                                    </div>
                                </td>
                                <td>{{form.late}}</td>
                                <td>{{form.undertime}}</td>
                                <td>{{form.payment_computation_for_work_done}}</td>
                                <td>{{form.overtime}}</td>
                                <td>{{form.payment_computation_overtime}}</td>
                            </tr>

                            {% endfor %}
                              <!-- end tbody -->
                        
                            
                          </table>
                          <div id="" style="display: none;">
                            <!-- Hidden -->
                            {{ formset.empty_form }}
                        </div>  
                    </div>
                    <div class="box-footer clearfix">
                        <button type="button" class="btn bg-navy margin pull-right" onclick="location.reload()">Reset Default</button>
                        <button id="btnApplyChanges" type="button" class="btn bg-purple margin pull-right">Apply Changes</button>
                    </div>
                </div> 
                {% endif %}
 
            </form>

        </div>
    </div>
</section>

<div class="modal fade" id="exclusive-modal-employee-cutoff"  data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title">Confirm Changes</h4>
        </div>
        <div class="modal-body">
          <p>Buy clicking continue, You will <strong>commit</strong> the changes done in the attendance&hellip;</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
          <button id="btnContinue" type="submit" class="btn btn-primary">Continue</button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
 
{% block js %}


{% endblock js %}

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script> 
<!-- DataTables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'js/employee_cutoff.js' %}"></script>

<!-- bootstrap time picker -->
<script src="{% static 'plugins/timepicker/bootstrap-timepicker.min.js' %}"></script>

<script>
    $('.select2').select2();
</script>
{% endblock main_content %}