LITS_System/LITS_System/urls.py
from django.contrib import admin
from django.urls import path, include
from application import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


handler404 = 'application.views.error_404'
handler500 = 'application.views.error_500'

 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.PayrollAttendanceIndexPage.as_view(), name="index"),
    path('employee/index/', views.PayrallAttendanceEmployeeIndexPage.as_view(), name="employee_index"),
    
    # Update password    
    path('accounts/password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # Password reset
    path('accounts/password_reset/',auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    # Login and register
    path('login/', views.login_page, name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('register/', views.register_page, name="register"), 

    path('application/', include('application.urls')),

    # path('error500/', views.error_500, name="error500"), 
    # path('error404/', views.error_404, name="error404"), 
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LITS_System/application/urls.py
from django.urls import path
from application import views

app_name = "application"

urlpatterns = [
    path('user/profile/', views.user_profile, name='user_profile'),
    path('user/new/profile/', views.new_profile, name='new_user_profile'),
    path('user/edit/profile/', views.edit_profile, name='edit_user_profile'),
    path('user/profile/image/', views.save_profile_image, name='save_profile_image'),
    path('user/profile/mobile_number/', views.add_mobile_number, name='add_mobile_number'),
    path('user/profile/mobile_number/delete/<int:id>/', views.delete_mobile_number, name='delete_mobile_number'),
    path('user/profile/skill/', views.add_skill, name='add_skill'),
    path('user/profile/skill/delete/<int:id>/', views.delete_skill, name='delete_skill'),
    path('user/new/company/details/', views.new_company_details, name='new_company_details'),
    path('user/edit/company/details/', views.edit_company_details, name='edit_company_details'),
    path('user/profile/telephone_number/', views.add_telephone_number, name='add_telephone_number'),
    path('user/profile/telephone_number/delete/<int:id>/', views.delete_telephone_number, name='delete_telephone_number'),
    path('attendance/cutoff/', views.cut_off_page, name="cut_off_page"),    
    path('employees/employee/list/', views.employee_list_page, name="employee_list"),
    path('employees/employee/list/payroll/settings/<str:key>/', views.employee_payroll_base_salary_settings, name="employee_payroll_settings"),
    path('employees/employee/delete/<int:id>/', views.delete_employee, name="delete_employee"),
    path('attendance/cutoff/upload/', views.upload_attendance, name="upload_attendance"),
    path('attendance/cutoff/delete/<int:id>/', views.delete_attendance, name="delete_attendance"),
    path('employees/attendance/view/<str:pk>/', views.employee_attendance, name="employee_attendance_view"),
    path('employees/attendance/view/cutoff/<str:pk>/<int:id>/', views.employee_attendance_cutoff, name="employee_attendance_cut_off_view"),
    path('employees/attendance/view/cutoff/manual/<str:pk>/<int:id>/', views.employee_attendance_manual_configuration, name="employee_attendance_cut_off_manual"),
    path('employees/payroll/manage/', views.employee_payroll_page, name="employee_payroll_manage"),
    path('employees/payroll/manage/cutoff/<int:id>/', views.employee_payroll_employee_list, name="employee_payroll_manage_employee_list"),
    path('employees/payroll/manage/cutoff/create/payroll/<str:key>/<int:id>/', views.employee_create_payroll, name="employee_create_payroll"),
    path('employees/payroll/manage/cutoff/edit/payroll/<str:key>/<int:id>/', views.employee_edit_payroll, name="employee_edit_payroll"),
    path('employees/payroll/manage/cutoff/delete/payroll/<str:key>/<int:id>/', views.employee_delete_payroll, name="employee_delete_payroll"),
    path('employees/manage/leaves/', views.employee_manage_leaves, name="employee_manage_leaves_page"),
    path('employees/manage/leaves/view/<int:id>/', views.employee_view_employee_leaves, name="employee_view_employee_leaves_page"),
    path('employees/manage/iteneraries/', views.employee_manage_itenerary, name="employee_manage_iteneraries_page"),
    path('employees/manage/iteneraries/view/<int:id>/', views.employee_view_itenerary, name="employee_view_iteneraries_page"),
    path('employees/manage/admin/concerns/', views.employee_manage_concerns, name="employee_manage_concerns_page"),
    path('employees/manage/admin/concerns/create/', views.employee_create_concern, name="employee_create_concerns_page"),
    path('employees/manage/admin/concerns/edit/<int:id>/', views.employee_edit_concern, name="employee_edit_concerns_page"),
    path('employees/manage/admin/concerns/view/<int:id>/', views.employee_view_concern, name="employee_view_concerns_page"),
    path('employees/manage/admin/concerns/delete/<int:id>/', views.employee_delete_concern , name="employee_delete_concerns_page"),
    path('employees/manage/admin/concerns/inbox/', views.employee_manage_inbox_concern, name="employee_manage_inbox_concerns_page"),
    path('employees/manage/admin/concerns/reply/<int:id>/', views.employee_reply_concern , name="employee_reply_concerns_page"),
    path('employees/manage/reports/', views.reports_page, name="employee_reports"),
    
    path('users/nofitications/manager/delete/<int:id>/', views.read_notifications, name="users_notifications_delete"),
    path('users/nofitications/manager/delete/all/', views.read_all_notifications, name="users_notifications_delete_all"),
    path('users/maintainancepage/',views.maintainance_page, name="users_maintainance_page"),


    #employee side
    path('employee/profile/', views.employee_profile, name='employee_profile'),
    path('employee/attendance/cutoffandpayroll/', views.side_employee_cut_off_payroll_page, name="employee_side_cutoff_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/attendance/<int:id>/', views.side_employee_cut_off_page, name="employee_side_cutoff_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/<int:id>/', views.side_employee_view_payroll_page, name="employee_side_view_payroll_page"),
    path('employee/attendance/cutoffandpayroll/view/payroll/print/<int:id>/', views.side_employee_print_payroll_page, name="employee_side_print_payroll_page"),
    path('employee/manage/leaves/', views.side_employee_manage_leaves_page, name="employee_side_manage_leaves_page"),
    path('employee/manage/leaves/create/', views.side_employee_create_leave_form, name="employee_side_create_leave_form"),
    path('employee/manage/leaves/edit/<int:id>/', views.side_employee_edit_leave_form, name="employee_side_edit_leave_form"),
    path('employee/manage/leaves/delete/<int:id>/', views.side_employee_delete_leave_form, name="employee_side_delete_leave_form"),
    path('employee/manage/leaves/view/<int:id>/', views.side_employee_view_leave_form, name="employee_side_view_leave_form"),
    path('employee/manage/iteneraries/', views.side_employee_manage_inteneraries, name="employee_side_manage_iteneraries_page"),
    path('employee/manage/iteneraries/create/', views.side_employee_create_inteneraries, name="employee_side_create_iteneraries_page"),
    path('employee/manage/iteneraries/edit/<int:id>/', views.side_employee_edit_inteneraries, name="employee_side_edit_iteneraries_page"),
    path('employee/manage/iteneraries/delete/<int:id>/', views.side_employee_delete_inteneraries, name="employee_side_delete_iteneraries_page"),
    path('employee/manage/iteneraries/view/<int:id>/', views.side_employee_view_itenerary_form, name="employee_side_view_iteneraries_page"),
    path('employee/manage/concerns/', views.side_employee_manage_concerns, name="employee_side_manage_concerns_page"),
    path('employee/manage/concerns/create/', views.side_employee_create_concern, name="employee_side_create_concerns_page"),
    path('employee/manage/concerns/edit/<int:id>/', views.side_employee_edit_concern, name="employee_side_edit_concerns_page"),
    path('employee/manage/concerns/delete/<int:id>/', views.side_employee_delete_concern, name="employee_side_delete_concerns_page"),
    path('employee/manage/concerns/view/<int:id>/', views.side_employee_view_concern, name="employee_side_view_concerns_page"),
    path('employee/manage/concerns/inbox/', views.side_employee_manage_inbox_concern, name="employee_side_manage_inbox_concerns_page"),
    path('employee/manage/concerns/reply/<int:id>/', views.side_employee_reply_concern, name="employee_side_reply_concerns_page"),
    path('employee/maintainancepage/', views.employee_side_maintainance_page, name="employee_side_maintainance_page"),
    
]

LITS_System/application/templates/concerns/employee_create_concern.html
<form class="create-admin-concern-form" method="POST" data-url="{% url 'application:employee_create_concerns_page' %}"> 
    {% csrf_token %}
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create concern form</h4>
    </div>
    <div class="modal-body">
        {% if form.errors %}
        <div class="callout callout-danger">
            <h4>Oops! Form Error!</h4>
            <p><strong>Please fix the error and try to save again!</strong></p>
            <p></p>
            {{ form.subject.errors|striptags }}  
            {{ form.message.errors|striptags }}   
            {{ form.errors|striptags}}
        </div>
        {% endif %}
        <div class="form-group">
            <label for="{{ form.receiver.id_for_label}}">To:</label>  
            {{ form.receiver}}
        </div> 
        <div class="form-group">
            <label for="{{form.subject.id_for_label}}">Subject:</label>
            <div class="input-group">
                <div class="input-group-addon">
                    <i class="fa fa-fw fa-envelope"></i>
                </div>
                {{ form.subject}}
            </div> 
        </div>  
        <div class="form-group">
            <label for="{{form.message.id_for_label}}">Message:</label>
            {{ form.message}}
        </div>  
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-success">Save</button>
      </div>
</form>

LITS_System/application/templates/concerns/employee_manage_concern.html
{% extends 'index.html' %} 
{% load staticfiles %} 
{% load humanize %} 
{% block title %} 
Manage Employee Concerns
{% endblock title%} 

{% block css %}
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">


<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
<!-- bootstrap datepicker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/all.css' %}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="{% static 'plugins/timepicker/bootstrap-timepicker.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

<!-- Google Font -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
 

<link rel="stylesheet" href="{% static 'css/loading-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/loading.css' %}">

{% endblock css %}

{% block nav_dashboard %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
    </a>
    <ul class="treeview-menu">
        <li class=""><a href="{% url 'index' %}"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
        <!-- <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li> -->
    </ul>
</li>
{% endblock nav_dashboard %}


{% block nav_employees %}
<li class="active treeview">
    <a href="#">
        <i class="fa fa-fw fa-group"></i> <span>Employees</span>
        <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
    </a>
    <ul class="treeview-menu">
        <li class=""><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i> List
        Employees</a></li>
        <li class=""><a href="{% url 'application:employee_payroll_manage' %}"><i class="fa fa-fw fa-credit-card"></i>
        Manage Payroll</a></li>
        <li class=""><a href="{% url 'application:employee_manage_leaves_page' %}"><i class="fa fa-fw fa-car"></i> Leaves </a></li>
        <li ><a href="{% url 'application:employee_manage_iteneraries_page' %}"><i class="fa fa-fw fa-calendar-times-o"></i> Iteneraries </a></li>
        <li class="active"><a href="{% url 'application:employee_manage_concerns_page' %}"><i class="fa fa-fw fa-commenting"></i> Concerns</a></li>
    </ul>
</li>
{% endblock nav_employees %}


{% block main_content %}

<section class="content-header">
    <h1>
        Employee Manage Concerns
        <small>Manage details</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> Home</a></li> 
        <li class="active"><i class="fa fa-fw fa-commenting"></i> Manage Concerns</li> 
    </ol>
</section>
<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Employee Concerns Table</h3>
                    <div class="box-tools"> 
                        <ul class="pagination pagination-sm no-margin pull-right">
                          <li><a id="newAdminConcern" href="{% url 'application:employee_create_concerns_page' %}" data-toggle="tooltip" title="File New Concern Form"><i class="fa fa-fw fa-commenting"></i> File Concern</a></li> 
                          <li><a  href="{% url 'application:employee_manage_inbox_concerns_page' %}" data-toggle="tooltip" title="Concern Inbox"><i class="fa fa-fw fa-inbox"></i>Inbox</a></li> 
                        </ul>
                    </div>
                </div>
                <div class="box-body">
                    <table id="tblAdminConcerns" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">ID</th> 
                                <th class="text-left">Subject</th>
                                <th class="text-left">Date Filed</th>                                
                                <th class="text-center" style="width: 15%">Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for concern in concern_list  %}
                                <tr>
                                    <td>
                                        <span class="badge bg-red"> {{ concern.id }}</span> 
                                    </td>
                                    <td>
                                        <span class="label label-info">{{ concern.subject }}</span>   
                                    </td>
                                    <td>
                                        <span class="label label-default">{{ concern.date_filed }}</span> 
                                    </td>
                                    <td>
                                        <div class="text-center">                                        
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-danger btn-delete" data-toggle="tooltip" title="Delete" data-url="{% url 'application:employee_delete_concerns_page' concern.id %}"><i class="fa fa-fw fa-trash"></i></button>
                                            <button type="button" class="btn btn-warning btn-view" data-toggle="tooltip" title="View" data-url="{% url 'application:employee_view_concerns_page' concern.id %}"><i class="fa fa-fw fa-eye"></i></button>
                                            <button type="button" class="btn btn-info btn-edit" data-toggle="tooltip" title="Edit" data-url="{% url 'application:employee_edit_concerns_page' concern.id %}"><i class="fa fa-fw fa-pencil-square-o"></i></button>
                                        </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>




{% block js %} 
{% endblock js %}

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>

<!-- DataTables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script> 
<script src="{% static 'js/employee_manage_concern.js' %}"></script>
  
{% endblock main_content %}

LITS_System/application/templates/concerns/employee_manage_inbox_concern.html
{% extends 'index.html' %} 
{% load staticfiles %} 
{% load humanize %} 
{% block title %} 
Manage Employee Inbox Concerns
{% endblock title%} 


{% block css %}
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="{% static 'bower_components/Ionicons/css/ionicons.min.css' %}">


<!-- daterange picker -->
<link rel="stylesheet" href="{% static 'bower_components/bootstrap-daterangepicker/daterangepicker.css' %}">
<!-- bootstrap datepicker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
<!-- iCheck for checkboxes and radio inputs -->
<link rel="stylesheet" href="{% static 'plugins/iCheck/all.css' %}">
<!-- Bootstrap Color Picker -->
<link rel="stylesheet"
    href="{% static 'bower_components/bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css' %}">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="{% static 'plugins/timepicker/bootstrap-timepicker.min.css' %}">
<!-- Select2 -->
<link rel="stylesheet" href="{% static 'bower_components/select2/dist/css/select2.min.css' %}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<!-- DataTables -->
<link rel="stylesheet" href="{% static 'bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/AdminLTE.min.css' %}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{% static 'dist/css/skins/_all-skins.min.css' %}">

<!-- Google Font -->
<link rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
 

<link rel="stylesheet" href="{% static 'css/loading-btn.css' %}">
<link rel="stylesheet" href="{% static 'css/loading.css' %}">

{% endblock css %}


{% block nav_dashboard %}
<li class="treeview">
    <a href="#">
        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
    </a>
    <ul class="treeview-menu">
        <li class=""><a href="{% url 'index' %}"><i class="fa fa-circle-o"></i> Dashboard v1</a></li>
        <!-- <li><a href="index2.html"><i class="fa fa-circle-o"></i> Dashboard v2</a></li> -->
    </ul>
</li>
{% endblock nav_dashboard %}


{% block nav_employees %}
<li class="active treeview">
    <a href="#">
        <i class="fa fa-fw fa-group"></i> <span>Employees</span>
        <span class="pull-right-container">
      <i class="fa fa-angle-left pull-right"></i>
    </span>
    </a>
    <ul class="treeview-menu">
        <li class=""><a href="{% url 'application:employee_list' %}"><i class="fa fa-fw fa-users"></i> List
        Employees</a></li>
        <li class=""><a href="{% url 'application:employee_payroll_manage' %}"><i class="fa fa-fw fa-credit-card"></i>
        Manage Payroll</a></li>
        <li class=""><a href="{% url 'application:employee_manage_leaves_page' %}"><i class="fa fa-fw fa-car"></i> Leaves </a></li>
        <li ><a href="{% url 'application:employee_manage_iteneraries_page' %}"><i class="fa fa-fw fa-calendar-times-o"></i> Iteneraries </a></li>
        <li class="active"><a href="{% url 'application:employee_manage_concerns_page' %}"><i class="fa fa-fw fa-commenting"></i> Concerns</a></li>
    </ul>
</li>
{% endblock nav_employees %}


{% block main_content %}
<section class="content-header">
    <h1>
        Employee Manage Inbox Concerns
        <small>Manage details</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}"><i class="fa fa-dashboard"></i> Home</a></li> 
        <li><a href="{% url 'application:employee_manage_concerns_page' %}"><i class="fa fa-fw fa-commenting"></i> Manage Concerns</a></li> 
        <li class="active"><i class="fa fa-fw fa-inbox"></i> Inbox Concerns</li> 
    </ol>
</section>

<section class="content">
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Employee Inbox Concerns Table</h3> 
                </div>
                <div class="box-body">
                    <table id="tblAdminInboxConcerns" class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th style="width: 5%">ID</th> 
                                <th class="text-left">From</th>
                                <th class="text-left">Subject</th>
                                <th class="text-left">Date Filed</th>                                
                                <th class="text-center" style="width: 15%">Action</th>
                            </tr>
                        </thead>
                        <tbody>

                            {% for concern in concern_list  %}
                                <tr>
                                    <td>
                                        <span class="badge bg-red"> {{ concern.id }}</span> 
                                    </td>
                                    <td>
                                        <span class="label label-warning">{{ concern.sender }}</span>   
                                    </td>
                                    <td>
                                        <span class="label label-info">{{ concern.subject }}</span>   
                                    </td>
                                    <td>
                                        <span class="label label-default">{{ concern.date_filed }}</span> 
                                    </td> 
                                    <td>
                                        <div class="text-center">                                        
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-success btn-reply" data-toggle="tooltip" title="Reply" data-url="{% url 'application:employee_reply_concerns_page' concern.id  %}"><i class="fa fa-fw fa-mail-reply"></i>Reply</button> 
                                        </div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>



{% block js %} 
{% endblock js %}

<!-- jQuery 3 -->
<script src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'bower_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'bower_components/fastclick/lib/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'bower_components/select2/dist/js/select2.full.min.js' %}"></script>

<!-- DataTables -->
<script src="{% static 'bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script> 
<script src="{% static 'js/employee_manage_inbox_concern.js' %}"></script>
  
{% endblock main_content %}